import type { LifecyclePhase, MasterMoment } from "./moment";

export const LIFECYCLE_PHASES: { key: LifecyclePhase; no: string; label: string }[] = [
  { key: "START", no: "01", label: "Start" },
  { key: "BUILD", no: "02", label: "Build" },
  { key: "LAUNCH", no: "03", label: "Launch" },
  { key: "OPERATE", no: "04", label: "Operate" },
  { key: "GROW", no: "05", label: "Grow" },
  { key: "CHANGE", no: "06", label: "Change" },
  { key: "EXIT", no: "07", label: "Exit / Legacy" },
];

export const MASTER_MOMENTS: MasterMoment[] = [
  {
    code: "EBM Start",
    no: 1,
    phase: "START",
    description: "เริ่มต้นธุรกิจ / ตั้งบริษัท / ตั้งแบรนด์",
    color: "#06b6d4",
    discoveryQuestions: [
      "จดทะเบียนบริษัทแล้วหรือยัง?",
      "มีชื่อแบรนด์ / โลโก้แล้วหรือไม่?",
      "กลุ่มลูกค้าเป้าหมายคือใคร?",
      "วางแผนเปิดตัวเมื่อไร?",
      "Budget เริ่มต้นโดยประมาณ?",
    ],
    nextMoments: ["EBM Build", "EBM Hire"],
  },
  {
    code: "EBM Build",
    no: 2,
    phase: "BUILD",
    description: "สร้าง Brand / Digital / Store / Infrastructure",
    color: "#3b82f6",
    discoveryQuestions: [
      "กำลังสร้างอะไรอยู่ (ร้าน / เว็บ / แบรนด์)?",
      "มี Brand Guideline แล้วหรือไม่?",
      "Timeline การก่อสร้าง / พัฒนา?",
      "ต้องการ Signage / ตกแต่งร้านหรือไม่?",
      "ใครเป็นผู้ตัดสินใจหลัก?",
    ],
    nextMoments: ["EBM Launch", "EBM Hire"],
  },
  {
    code: "EBM Hire",
    no: 3,
    phase: "BUILD",
    description: "Recruitment / New Team / Expansion",
    color: "#3b82f6",
    discoveryQuestions: [
      "รับพนักงานใหม่กี่ตำแหน่ง / กี่คน?",
      "เริ่มงานเมื่อไร?",
      "มี Uniform มาตรฐานหรือไม่?",
      "มี Welcome Kit สำหรับพนักงานใหม่หรือไม่?",
      "มี Onboarding Program หรือไม่?",
    ],
    nextMoments: ["EBM Welcome", "EBM Engage"],
  },
  {
    code: "EBM Welcome",
    no: 4,
    phase: "OPERATE",
    description: "Employee / Customer / Partner Onboarding",
    color: "#6366f1",
    discoveryQuestions: [
      "Onboard ใคร (พนักงาน / ลูกค้า / Partner)?",
      "จำนวนกี่คนต่อรอบ?",
      "ความถี่ในการ Onboard?",
      "อยากให้ First Impression เป็นแบบไหน?",
      "Budget ต่อหัวโดยประมาณ?",
    ],
    nextMoments: ["EBM Engage", "EBM Milestone"],
  },
  {
    code: "EBM Launch",
    no: 5,
    phase: "LAUNCH",
    description: "เปิดบริษัท ร้าน สาขา เว็บไซต์ สินค้า Campaign",
    color: "#22d3ee",
    discoveryQuestions: [
      "เปิดตัวอะไร / ที่ไหน?",
      "วันเปิดตัวคือวันไหน?",
      "มี Grand Opening Event หรือไม่?",
      "ต้องการของแจก / ของที่ระลึกหรือไม่?",
      "คาดว่ามีผู้ร่วมงานกี่คน?",
    ],
    nextMoments: ["EBM Thanks", "EBM Sell"],
  },
  {
    code: "EBM Sell",
    no: 6,
    phase: "OPERATE",
    description: "Lead / Sales / Consultation / First Order",
    color: "#6366f1",
    discoveryQuestions: [
      "สินค้า / บริการหลักคืออะไร?",
      "ทีมขายมีกี่คน?",
      "มี Sales Material พร้อมหรือไม่?",
      "ใช้ช่องทางขายอะไรบ้าง?",
      "เป้ายอดขายปีนี้?",
    ],
    nextMoments: ["EBM Deliver", "EBM Thanks"],
  },
  {
    code: "EBM Deliver",
    no: 7,
    phase: "OPERATE",
    description: "Sample / Production / Delivery / Handover",
    color: "#6366f1",
    discoveryQuestions: [
      "ส่งมอบอะไร / ให้ใคร?",
      "Delivery Date คือวันไหน?",
      "ต้องการ Packaging พิเศษหรือไม่?",
      "มี QC Requirement อะไรบ้าง?",
      "ต้องการ Handover Kit หรือไม่?",
    ],
    nextMoments: ["EBM Thanks", "EBM Repeat"],
  },
  {
    code: "EBM Thanks",
    no: 8,
    phase: "OPERATE",
    description: "Thank You / Appreciation",
    color: "#6366f1",
    discoveryQuestions: [
      "ขอบคุณใคร (ลูกค้า / พนักงาน / Partner)?",
      "โอกาสอะไร?",
      "จำนวนผู้รับกี่คน?",
      "Budget ต่อชิ้น?",
      "ต้องการ Personalization หรือไม่?",
    ],
    nextMoments: ["EBM Repeat", "EBM Engage"],
  },
  {
    code: "EBM Repeat",
    no: 9,
    phase: "GROW",
    description: "Reorder / Renewal / Repurchase",
    color: "#22c55e",
    discoveryQuestions: [
      "Order เดิมคืออะไร?",
      "ต้องการปรับเปลี่ยนอะไรจากรอบก่อน?",
      "จำนวน / Timeline รอบนี้?",
      "Feedback จากรอบก่อนเป็นอย่างไร?",
      "มีโอกาส Bundle เพิ่มหรือไม่?",
    ],
    nextMoments: ["EBM Milestone", "EBM Grow"],
  },
  {
    code: "EBM Engage",
    no: 10,
    phase: "OPERATE",
    description: "Community / CRM / Employee Engagement",
    color: "#6366f1",
    discoveryQuestions: [
      "Engage กลุ่มไหน?",
      "กิจกรรมอะไร / ความถี่แค่ไหน?",
      "เป้าหมายของกิจกรรมคืออะไร?",
      "จำนวนผู้เข้าร่วม?",
      "Budget ต่อกิจกรรม?",
    ],
    nextMoments: ["EBM Milestone", "EBM Celebrate"],
  },
  {
    code: "EBM Grow",
    no: 11,
    phase: "GROW",
    description: "Revenue / Team / Product / Customer Growth",
    color: "#22c55e",
    discoveryQuestions: [
      "โตด้านไหน (ยอดขาย / ทีม / สินค้า)?",
      "แผนการโตปีนี้เป็นอย่างไร?",
      "ต้องการ Support ด้านไหน?",
      "ทีมโตขึ้นกี่คน?",
      "มีแผนขยายสาขาหรือไม่?",
    ],
    nextMoments: ["EBM Expand", "EBM Hire"],
  },
  {
    code: "EBM Milestone",
    no: 12,
    phase: "GROW",
    description: "Anniversary / Promotion / Achievement",
    color: "#22c55e",
    discoveryQuestions: [
      "Milestone อะไร (ครบรอบ / เลื่อนตำแหน่ง)?",
      "วันสำคัญคือวันไหน?",
      "จัดงานฉลองหรือไม่?",
      "จำนวนผู้เกี่ยวข้อง?",
      "อยากให้พิเศษแค่ไหน?",
    ],
    nextMoments: ["EBM Celebrate", "EBM Season"],
  },
  {
    code: "EBM Celebrate",
    no: 13,
    phase: "GROW",
    description: "Award / Birthday / Team Win",
    color: "#22c55e",
    discoveryQuestions: [
      "ฉลองอะไร?",
      "วันงานคือวันไหน?",
      "จำนวนผู้ร่วมงาน?",
      "ต้องการของที่ระลึกหรือไม่?",
      "Theme งานเป็นแบบไหน?",
    ],
    nextMoments: ["EBM Engage", "EBM Season"],
  },
  {
    code: "EBM Season",
    no: 14,
    phase: "OPERATE",
    description: "New Year / CNY / Songkran / Annual Events",
    color: "#f59e0b",
    discoveryQuestions: [
      "เทศกาลไหน?",
      "ส่งให้ใคร (ลูกค้า / พนักงาน / Partner)?",
      "จำนวนกี่ชุด?",
      "Budget ต่อชุด?",
      "ต้องการส่งถึงเมื่อไร?",
    ],
    nextMoments: ["EBM Thanks", "EBM Repeat"],
  },
  {
    code: "EBM Expand",
    no: 15,
    phase: "GROW",
    description: "New Branch / Franchise / New Territory",
    color: "#22c55e",
    discoveryQuestions: [
      "เปิดสาขาที่ไหน?",
      "เปิดเมื่อไร?",
      "สาขาเดิมใช้ Brand Standard อะไร?",
      "พนักงานใหม่กี่คน?",
      "Packaging ต้องเพิ่มไหม?",
      "มี Grand Opening หรือไม่?",
      "ต้องการ Signage / POSM หรือไม่?",
      "Budget โดยประมาณ?",
      "Decision Maker คือใคร?",
      "Timeline Critical Date คือวันไหน?",
    ],
    nextMoments: ["EBM Launch", "EBM Hire"],
  },
  {
    code: "EBM Change",
    no: 16,
    phase: "CHANGE",
    description: "Rebrand / New CEO / Relocation / Restructure",
    color: "#f59e0b",
    discoveryQuestions: [
      "เปลี่ยนอะไร (แบรนด์ / ผู้บริหาร / ที่ตั้ง)?",
      "Effective Date คือวันไหน?",
      "สิ่งที่ต้อง Update มีอะไรบ้าง?",
      "สื่อสารกับใครบ้าง?",
      "Budget สำหรับการเปลี่ยนแปลง?",
    ],
    nextMoments: ["EBM Launch", "EBM Engage"],
  },
  {
    code: "EBM Recover",
    no: 17,
    phase: "CHANGE",
    description: "Complaint / Delay / Error / Crisis",
    color: "#ef4444",
    discoveryQuestions: [
      "ปัญหาที่เกิดขึ้นคืออะไร?",
      "ลูกค้าได้รับผลกระทบแค่ไหน?",
      "แก้ไขไปแล้วอย่างไร?",
      "ต้องการ Gesture ขอโทษแบบไหน?",
      "ใครคือผู้ที่ต้องได้รับการดูแล?",
    ],
    nextMoments: ["EBM Thanks", "EBM Return"],
  },
  {
    code: "EBM Return",
    no: 18,
    phase: "CHANGE",
    description: "Win-back / Reactivation / Rehire",
    color: "#a855f7",
    discoveryQuestions: [
      "หายไปนานแค่ไหน / เพราะอะไร?",
      "Order ล่าสุดคืออะไร?",
      "สถานการณ์ธุรกิจตอนนี้เป็นอย่างไร?",
      "มี Moment ใหม่อะไรกำลังเกิดขึ้น?",
      "Offer อะไรที่จะดึงกลับมาได้?",
    ],
    nextMoments: ["EBM Repeat", "EBM Engage"],
  },
  {
    code: "EBM Farewell",
    no: 19,
    phase: "EXIT",
    description: "Resignation / Retirement / Contract End",
    color: "#64748b",
    discoveryQuestions: [
      "ใครกำลังจะจากไป (เกษียณ / ลาออก)?",
      "วันสุดท้ายคือวันไหน?",
      "อยากส่งท้ายแบบไหน?",
      "จำนวนผู้ร่วมงาน?",
      "ต้องการของที่ระลึกพิเศษหรือไม่?",
    ],
    nextMoments: ["EBM Hire", "EBM Engage"],
  },
  {
    code: "EBM Close",
    no: 20,
    phase: "EXIT",
    description: "Closure / M&A / Founder Exit / Legacy",
    color: "#334155",
    discoveryQuestions: [
      "เกิดอะไรขึ้น (ปิดกิจการ / ควบรวม)?",
      "Timeline คือเมื่อไร?",
      "ต้องการเก็บ Legacy อะไรไว้?",
      "มีการสื่อสารกับ Stakeholder อย่างไร?",
      "มีธุรกิจใหม่ต่อจากนี้หรือไม่?",
    ],
    nextMoments: ["EBM Start"],
  },
];

export const momentByCode = new Map<string, MasterMoment>(MASTER_MOMENTS.map((m) => [m.code, m]));

export function momentColor(code: string): string {
  return momentByCode.get(code)?.color ?? "#94a3b8";
}
