/**
 * Generates seed/seed.sql from the mock dataset so D1 starts with the same
 * data the mock adapter serves. Run: npm run generate-seed
 * Apply: npx wrangler d1 execute moment-os --file=seed/seed.sql [--remote]
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { MASTER_MOMENTS } from "../lib/domain/master-moments";
import { ACCOUNTS } from "../lib/infrastructure/mock/accounts";
import { MOMENT_EVENTS } from "../lib/infrastructure/mock/events";
import { APPOINTMENTS, OPPORTUNITIES } from "../lib/infrastructure/mock/opportunities";
import { SOLUTIONS } from "../lib/infrastructure/mock/solutions";
import { USERS } from "../lib/infrastructure/mock/users";

const ORG = "ORG-001";
const NOW = "2026-08-22T00:00:00Z";

const q = (v: string | number | null | undefined): string => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
};
const b = (v: boolean): string => (v ? "1" : "0");

const CLEAR_ORDER = [
  "appointments", "opportunity_solutions", "opportunities",
  "moment_event_solutions", "moment_event_stakeholders", "moment_signals",
  "moment_events", "solution_relations", "solution_packages",
  "solution_industries", "solution_stakeholders", "solutions",
  "orders_external", "account_whitespace", "contacts", "accounts",
  "master_moment_next", "moment_discovery_questions", "master_moments",
  "users", "organizations",
];

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  ...CLEAR_ORDER.map((t) => `DELETE FROM ${t};`),
  `INSERT INTO organizations (id, name, created_at) VALUES (${q(ORG)}, 'Every Business Moments', ${q(NOW)});`,
];

for (const u of USERS) {
  lines.push(
    `INSERT INTO users (id, organization_id, name, nickname, role, center, created_at) VALUES (${q(u.id)}, ${q(ORG)}, ${q(u.name)}, ${q(u.nickname)}, ${q(u.role)}, ${q(u.center ?? null)}, ${q(NOW)});`,
  );
}

for (const m of MASTER_MOMENTS) {
  lines.push(
    `INSERT INTO master_moments (code, no, phase, description, color, active) VALUES (${q(m.code)}, ${m.no}, ${q(m.phase)}, ${q(m.description)}, ${q(m.color)}, 1);`,
  );
}
// Second pass — questions and next-moment relations reference moments that
// must all exist first (forward references would violate FKs).
for (const m of MASTER_MOMENTS) {
  m.discoveryQuestions.forEach((question, i) => {
    lines.push(
      `INSERT INTO moment_discovery_questions (id, moment_code, ordinal, question) VALUES (${q(`MDQ-${m.no}-${i + 1}`)}, ${q(m.code)}, ${i + 1}, ${q(question)});`,
    );
  });
  for (const next of m.nextMoments) {
    lines.push(
      `INSERT INTO master_moment_next (moment_code, next_moment_code) VALUES (${q(m.code)}, ${q(next)});`,
    );
  }
}

for (const a of ACCOUNTS) {
  lines.push(
    `INSERT INTO accounts (id, organization_id, name, industry, employee_size, location, branch_count, tier, owner_id, customer_since, lifetime_value, gross_profit, health, account_score, notes, created_at, updated_at) VALUES (${q(a.id)}, ${q(ORG)}, ${q(a.name)}, ${q(a.industry)}, ${a.employeeSize}, ${q(a.location)}, ${a.branchCount}, ${q(a.tier)}, ${q(a.ownerId)}, ${q(a.customerSince)}, ${a.ltv}, ${a.grossProfit}, ${q(a.health)}, ${a.accountScore}, ${q(a.notes ?? null)}, ${q(NOW)}, ${q(NOW)});`,
  );
  a.contacts.forEach((c, i) => {
    lines.push(
      `INSERT INTO contacts (id, account_id, name, role, phone, is_primary, created_at) VALUES (${q(`CT-${a.id}-${i + 1}`)}, ${q(a.id)}, ${q(c.name)}, ${q(c.role)}, ${q(c.phone)}, ${b(i === 0)}, ${q(NOW)});`,
    );
  });
  for (const [category, bought] of Object.entries(a.whitespace)) {
    lines.push(
      `INSERT INTO account_whitespace (account_id, category, bought) VALUES (${q(a.id)}, ${q(category)}, ${b(bought)});`,
    );
  }
  a.purchases.forEach((p, i) => {
    lines.push(
      `INSERT INTO orders_external (id, organization_id, account_id, item, moment_code, order_date, revenue, status, last_synced_at) VALUES (${q(`ORD-${a.id}-${i + 1}`)}, ${q(ORG)}, ${q(a.id)}, ${q(p.item)}, ${q(p.moment)}, ${q(p.date)}, ${p.amount}, 'Delivered', ${q(NOW)});`,
    );
  });
}

for (const s of SOLUTIONS) {
  lines.push(
    `INSERT INTO solutions (id, organization_id, name, moment_code, starting_price, average_wallet, gross_margin_target, lead_time_days, production_required, recommended_offline, next_moment, active, created_at) VALUES (${q(s.id)}, ${q(ORG)}, ${q(s.name)}, ${q(s.moment)}, ${s.startingPrice}, ${s.averageWallet}, ${s.grossMarginTarget}, ${s.leadTimeDays}, ${b(s.productionRequired)}, ${b(s.recommendedOffline)}, ${q(s.nextMoment)}, 1, ${q(NOW)});`,
  );
  for (const st of s.stakeholders) {
    lines.push(
      `INSERT INTO solution_stakeholders (solution_id, stakeholder) VALUES (${q(s.id)}, ${q(st)});`,
    );
  }
  for (const ind of s.industries) {
    lines.push(
      `INSERT INTO solution_industries (solution_id, industry) VALUES (${q(s.id)}, ${q(ind)});`,
    );
  }
  (s.packages ?? []).forEach((p, i) => {
    lines.push(
      `INSERT INTO solution_packages (id, solution_id, name, starting_price, items_json) VALUES (${q(`${s.id}-PKG-${i + 1}`)}, ${q(s.id)}, ${q(p.name)}, ${p.startingPrice}, ${q(JSON.stringify(p.items))});`,
    );
  });
}
// Second pass — cross-sell relations may point at solutions defined later.
for (const s of SOLUTIONS) {
  for (const target of s.crossSellSolutionIds) {
    lines.push(
      `INSERT INTO solution_relations (source_solution_id, target_solution_id, relation_type) VALUES (${q(s.id)}, ${q(target)}, 'CROSS_SELL');`,
    );
  }
}

for (const e of MOMENT_EVENTS) {
  lines.push(
    `INSERT INTO moment_events (id, organization_id, account_id, moment_code, sub_moment, trigger_source, trigger_detail, detected_at, expected_event_date, score_business_fit, score_intent, score_timing, score_wallet, score_relationship, potential_wallet_min, potential_wallet_max, recommended_action, owner_id, status, next_expected_moment, channel, created_at, updated_at) VALUES (${q(e.id)}, ${q(ORG)}, ${q(e.accountId)}, ${q(e.momentType)}, ${q(e.subMoment)}, ${q(e.triggerSource)}, ${q(e.triggerDetail)}, ${q(e.detectedAt)}, ${q(e.expectedEventDate)}, ${e.score.businessFit}, ${e.score.intent}, ${e.score.timing}, ${e.score.wallet}, ${e.score.relationship}, ${e.potentialWalletMin}, ${e.potentialWalletMax}, ${q(e.recommendedAction)}, ${q(e.ownerId)}, ${q(e.status)}, ${q(e.nextExpectedMoment)}, ${q(e.channel ?? null)}, ${q(NOW)}, ${q(NOW)});`,
  );
  for (const st of e.stakeholders) {
    lines.push(
      `INSERT INTO moment_event_stakeholders (moment_event_id, stakeholder) VALUES (${q(e.id)}, ${q(st)});`,
    );
  }
  for (const sid of e.recommendedSolutionIds) {
    lines.push(
      `INSERT INTO moment_event_solutions (moment_event_id, solution_id) VALUES (${q(e.id)}, ${q(sid)});`,
    );
  }
}

for (const o of OPPORTUNITIES) {
  lines.push(
    `INSERT INTO opportunities (id, organization_id, moment_event_id, account_id, name, expected_revenue, expected_gp, close_date, stage, owner_id, next_action, sla_hours, channel, created_at, updated_at) VALUES (${q(o.id)}, ${q(ORG)}, ${q(o.momentEventId)}, ${q(o.accountId)}, ${q(o.name)}, ${o.expectedRevenue}, ${o.expectedGP}, ${q(o.closeDate)}, ${q(o.stage)}, ${q(o.ownerId)}, ${q(o.nextAction)}, ${o.slaHours ?? "NULL"}, ${q(o.channel ?? null)}, ${q(NOW)}, ${q(NOW)});`,
  );
}

for (const a of APPOINTMENTS) {
  lines.push(
    `INSERT INTO appointments (id, organization_id, account_id, moment_event_id, center, datetime, consultant_id, need, expected_wallet, samples_json, status, created_at) VALUES (${q(a.id)}, ${q(ORG)}, ${q(a.accountId)}, ${q(a.momentEventId)}, ${q(a.center)}, ${q(a.datetime)}, ${q(a.consultantId)}, ${q(a.need)}, ${a.expectedWallet}, ${q(JSON.stringify(a.samples))}, ${q(a.status)}, ${q(NOW)});`,
  );
}

mkdirSync("seed", { recursive: true });
writeFileSync("seed/seed.sql", lines.join("\n") + "\n");
console.log(`seed/seed.sql written — ${lines.length} statements`);
